services:
  mongodb:
    image: mongo:8.0.4-noble
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - shrimp-url-dev-data:/data/db
      - ./scripts/mongo/:/docker-entrypoint-initdb.d
      - ./scripts/mongo:/home/mongodb

    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "secret"

volumes:
  shrimp-url-dev-data:
