version: '3.9'

services:
  mongodb:
    image: mongo:5.0.6-focal
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./scripts/mongo/:/docker-entrypoint-initdb.d
      - ./scripts/mongo:/home/mongodb
      - shrimp-url-dev-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_DATABASE=$MONGO_DATABASE
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD

volumes:
  shrimp-url-dev-data:
