FROM node:20.18.1-alpine3.21

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ARG PNPM_VERSION=9.15.3

# Install packages needed for node-gyp and dev runtime.
RUN apk update && apk upgrade && \
  apk add --no-cache \
  libc6-compat \
  procps \
  build-base \
  python3 && \
  corepack enable && \
  corepack prepare pnpm@${PNPM_VERSION} --activate && \
  rm -rf /var/cache/apk/*
