
FROM shrimp/base-node-builder AS deps

WORKDIR /app
COPY ./package.json \
  ./pnpm-lock.yaml \
  ./pnpm-workspace.yaml \
  ./tsconfig.json \
  ./

WORKDIR /app/libs/server
COPY ./libs/server/package.json ./

WORKDIR /app
RUN --mount=type=cache,id=pnpm,target=/pnpm/store CI=1 pnpm i --config.dedupe-peer-dependents=false


# -------------------------------------------------------------
FROM shrimp/base-node-builder AS build

WORKDIR /app
COPY --from=deps app/tsconfig.json ./
COPY --from=deps app/package.json ./
COPY --from=deps app/pnpm-workspace.yaml ./
COPY --from=deps app/node_modules ./node_modules

WORKDIR /app/libs/server
COPY --from=deps app/libs/server/node_modules ./node_modules
COPY ./libs/server ./

RUN --mount=type=secret,id=build_env,dst=.env pnpm build:prod

WORKDIR /app
RUN rm -rf node_modules

WORKDIR /app/libs/server
RUN rm -rf node_modules

RUN --mount=type=secret,id=build_env,dst=.env pnpm install --prod --config.dedupe-peer-dependents=false


# -------------------------------------------------------------
FROM shrimp/base-node-runner AS runner

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 api

WORKDIR /app
COPY --link --from=build app/tsconfig.json ./
COPY --link --from=build app/package.json ./
COPY --link --from=build app/pnpm-workspace.yaml ./
COPY --link --chown=api:nodejs --from=build app/node_modules ./node_modules

WORKDIR /app/libs/server
COPY --link --chown=api:nodejs --from=build app/libs/server/node_modules ./node_modules
COPY --link --chown=api:nodejs --from=build app/libs/server/dist ./dist
COPY --link --chown=api:nodejs --from=build app/libs/server/package.json ./

USER node

ENTRYPOINT ["node", "dist/index.js"]
