services:
  mongodb:
    image: mongo:8.0.4-noble
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./scripts/mongo/:/docker-entrypoint-initdb.d
      - ./scripts/mongo:/home/mongodb
      - shrimp-url-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    networks:
      - shrimp-network

  api:
    image: shrimp/server:latest
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - DOMAIN=$DOMAIN
      - SERVER_HOST=$SERVER_HOST
      - SERVER_PORT=$SERVER_PORT
      - MONGO_DATABASE=$MONGO_DATABASE
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - MONGO_HOSTNAME=$MONGO_HOSTNAME
      - MONGO_PORT=$MONGO_PORT
      - NODE_ENV=production
    command: ['sh', '-c', 'yarn start']
    networks:
      - shrimp-network
    depends_on:
      - mongodb

  web:
    image: shrimp/web:latest
    container_name: web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - ${CLIENT_SERVER_PORT}:${CLIENT_SERVER_PORT}
    environment:
      BASE_URL: $SERVER_HOST
    command: ['sh', '-c', 'node server.js']
    networks:
      - shrimp-network
    depends_on:
      - api

  cors:
    build: ./libs/cors
    container_name: webserver
    restart: unless-stopped
    ports:
      - '80:80'
    networks:
      - shrimp-network
    depends_on:
      - api
      - web

volumes:
  shrimp-url-data:

networks:
  shrimp-network:
    driver: bridge
